<a href="https://colab.research.google.com/github/Ariahuhenrietha/Ariahuhenrietha/blob/main/Another_copy_of_scientfic__computingprep_week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Define a vector
v = np.array([1, 2, 3])

# Define a matrix
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

print("Vector v:", v)
print("Matrix A:\n", A)

Vector v: [1 2 3]
Matrix A:
 [[1 2]
 [3 4]
 [5 6]]


In [ ]:
B = np.array([[1, 2, 3],
              [4, 5, 6]])

result = A @ B   # matrix multiplication

print("A shape:", A.shape)
print("B shape:", B.shape)
print("A @ B =\n", result)

A shape: (3, 2)
B shape: (2, 3)
A @ B =
 [[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [ ]:
A = np.array([[3, 1],
              [1, 2]])

b = np.array([9, 8])

x = np.linalg.solve(A, b)

print("Solution x:", x)

Solution x: [2. 3.]


In [ ]:
A = np.array([[1, 2],
              [3, 4]])     # shape (2, 2)

B = np.array([[1, 2],
              [3, 4],
              [5, 6]])     # shape (3, 2)

A @ B

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [ ]:
A = np.array([[1, 2],
              [3, 4]])     # shape (2, 2)

B = np.array([[1, 2],
              [3, 4],
              [5, 6]])     # shape (3, 2)

A @ B

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)